# format terraform files
format:
    terraform fmt -recursive

# lint files
lint:
    uvx prek run --all-files

# update autogenerated documentation
# WARNING: some resource links are bad and need manual fixup :/
docs:
    terraform-docs .
