# format terraform files
format:
    terraform fmt -recursive

# lint files
lint:
    #!/usr/bin/env bash
    set -e

    terraform fmt -recursive --check
    terraform init
    terraform validate
    tflint -f compact --recursive

# update autogenerated documentation
# WARNING: some resource links are bad and need manual fixup :/
docs:
    terraform-docs .
